[tool.poetry]
name = "minimiko"
version = "0.2.0"
description = ""
authors = ["Pedro Gracia <me@lasarux.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
paramiko = "^3.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
